# Generated by Django 4.1.7 on 2023-04-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_seat_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='occupant_email',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='occupant_first_name',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='occupant_last_name',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='purchase_time',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_no',
        ),
        migrations.AddField(
            model_name='seat',
            name='class_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First')], default='Economy', max_length=10),
        ),
        migrations.AddField(
            model_name='seat',
            name='column',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(default=1, max_length=5),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='Dashboard.flight'),
        ),
    ]
